/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { SwapERC20 } from "./SwapERC20";
export type { SwapFactory } from "./SwapFactory";
export type { SwapPair } from "./SwapPair";
export type { SwapRouter } from "./SwapRouter";
