/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwapCallee,
  ISwapCalleeInterface,
} from "../../../contracts/interfaces/ISwapCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "swapCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwapCallee__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapCalleeInterface {
    return new Interface(_abi) as ISwapCalleeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISwapCallee {
    return new Contract(address, _abi, runner) as unknown as ISwapCallee;
  }
}
